name: FreeWorldArt
favicon: null
layout_spectrum: 0.5784103
typography_spectrum: 0.9049408
title: Free World Art
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c3271a'
    - '#0d0c08'
    - '#ac5709'
    - '#581e0c'
    - '#f2a823'
  brandStrength: 0.875
  lightness: 0.5
  saturation: 0.6729323
  rhythmicContrast: 1
purpose: []
